version: "3.9"

services:
  web:
    build: ./docker
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run ${APP_ENV}"

  mongo-db:
    image: mongo:latest
    container_name: mongo
    env_file:
      - .env
    ports:
      - "27015:27017"
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - .env
    links:
      - mongo-db
    restart: always
    depends_on:
      - mongo-db